name: Run Tests
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: workout_test
          POSTGRES_PASSWORD: ""

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup System Dependencies
      run: |
        sudo apt-get update && sudo apt-get install libpq-dev

    - name: Setup App Dependencies
      run: |
        gem install bundler
        bundle update --ruby
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: bundle exec rails test
