name: Run Tests
on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup App Dependencies
      run: |
        gem install bundler
        bundle update --ruby
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: bundle exec rails test
