name: Run Tests
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: workout_test
          POSTGRES_PASSWORD: ""

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup Ruby
      run: sudo snap install ruby --classic

    - name: Setup Dependencies
      run: |
        sudo gem install bundler
        sudo bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: bundle exec rails test
