name: Run Tests
on: push

jobs:
  build:
    container:
      image: ruby:2.6-alpine

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: workout_test
          POSTGRES_PASSWORD: ""

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup System Dependencies
      run: |
        apk add --update --no-cache \
          build-base \
          nodejs \
          postgresql-dev \
          tzdata

    - name: Setup App Dependencies
      run: |
        gem install bundler
        bundle update --ruby --bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: bundle exec rails test
