name: Tests
on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Needed because the postgres container does not provide a healthcheck.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.5'

    - name: Setup App Dependencies
      run: |
        sudo apt-get install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      env:
        RAILS_ENV: test
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      env:
        RAILS_ENV: test
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: bundle exec rails test
