name: Run Tests
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        ruby: [2.6, 3.x]

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: workout_test
          POSTGRES_PASSWORD: ""

    name: Test ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Setup Dependencies
      run: |
        gem install bundler
        bundle update --ruby --bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      run: bundle exec rails test
