name: Run Tests
on: push

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        options:
          hostname: db

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup App Dependencies
      run: |
        sudo apt-get install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      env:
        RAILS_ENV: test
        # PGHOST: postgres
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run Tests
      env:
        RAILS_ENV: test
        # PGHOST: postgres
      run: bundle exec rails test
